### PR TITLE
Bumps PAC4J version to 3.6.1

### PR DESCRIPTION
**Pull request by ihostage**
@leleuj What you think about release `1.1.0`?

### CODE REVIEW

**Comment by leleuj** [comment]
@ihostage I'll check that when I come back from holidays...

**Comment by leleuj** [comment]
@ihostage I will cut the release this week. Ping me if I forget.

**Comment by ihostage** [comment]
@leleuj ok 😉

**Comment by leleuj** [comment]
The v1.1.0 release should show up in the Maven central repository within a few hours.

**Pull request merged**
