### PR TITLE
#10 Bump Pac4j version to 3.4.0

### PR DESCRIPTION
**Pull request by ihostage**

### CODE REVIEW

**Comment by leleuj** [comment]
@ihostage : are we good for a 1.0.0 release of `lagom-pac4j`?

**Comment by ihostage** [comment]
@leleuj I think yes 😄

**Comment by leleuj** [comment]
I just released the version 1.0.0. It will show up within a few hours in the Maven central repository.

I'll make an announcement on the pac4j-announce mailing list. I let you handle the wiki and README updates as well as any announcement you'll find necessary (Lagom services mailing list?)

**Comment by leleuj** [comment]
There were two warnings regarding Javadoc you may want to fix for the next release:

```
    2 warnings
    [WARNING] Javadoc Warnings
    [WARNING] /Users/bidou/releases/lagom-pac4j/target/checkout/shared/src/main/java/org/pac4j/lagom/jwt/JwtAuthenticatorHelper.java:77: warning: no description for @throws
    [WARNING] * @throws ParseException
    [WARNING] ^
    [WARNING] /Users/bidou/releases/lagom-pac4j/target/checkout/shared/src/main/java/org/pac4j/lagom/jwt/JwtAuthenticatorHelper.java:78: warning: no description for @throws
    [WARNING] * @throws JOSEException
    [WARNING] ^
```

**Comment by ihostage** [comment]
> I just released the version 1.0.0. It will show up within a few hours in the Maven central repository.

It's great 🎉

> I'll make an announcement on the pac4j-announce mailing list. I let you handle the wiki and README updates as well as any announcement you'll find necessary (Lagom services mailing list?)

Thanks, Jerome! How I planned, I'll write a recipe ([Lagom Recipes](https://github.com/lagom/lagom-recipes)) and make announcements on the official Lagom Gitter channel.

And I have one question 😄 
I attached release note for tag `lagom-pac4j-parent-1.0.0`.
Can we change the pattern of name release tag? Now `lagom-pac4j-parent-X.Y.Z`. Maybe just `X.Y.Z`?

**Comment by leleuj** [comment]
Reading the [plugin doc](http://maven.apache.org/maven-release/maven-release-plugin/examples/prepare-release.html), I think so:

```xml
<configuration>
     <tagNameFormat>v@{project.version}</tagNameFormat>
</configuration>
```

**Pull request merged**
