### PR TITLE
Support initialize `JwtAuthenticator` by urls of JWKS

### PR DESCRIPTION
**Pull request by ihostage**

### CODE REVIEW

**Comment by ihostage** [comment]
Hi, @leleuj ! 👋 
Can you release `2.2.0` after reviewed and merged this PR? 😄

**Comment by leleuj** [comment]
Looks good to me. Will merge. I created a 2.1.x branch for older 2.1.x versions.

**Comment by leleuj** [comment]
@ihostage The release is in progress. It will show up soon in the Maven central repository...

**Comment by ihostage** [comment]
Thank you, Jerome! @leleuj

**Pull request merged**
